Repository show-karma/gap-app-v2, pull requests merged in 2024-09, with the labels that each got.

#269 feat: SEO updates + metadata changes
  app/project/[projectId]/grants/[grantUid]/impact-criteria/page.tsx
  app/project/[projectId]/grants/[grantUid]/milestones-and-updates/page.tsx
  app/project/[projectId]/grants/[grantUid]/page.tsx
  app/project/[projectId]/grants/[grantUid]/review-this-grant/page.tsx
  app/project/[projectId]/grants/layout.tsx
  app/project/[projectId]/impact/page.tsx
  app/project/[projectId]/layout.tsx
  app/sitemaps/projects/sitemap.ts
  public/sitemap-0.xml
Labels: enhancement

#270 fix: Group communities on multiple chains for search results
  components/Searchbar/SearchList.tsx
  utilities/communityHelpers.ts
Labels: on product review

#280 feat: sanitize inputs
  components/Forms/MilestoneUpdate.tsx
  components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/UpdateMilestone.tsx
  components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/VerifyGrantUpdateDialog.tsx
  components/Pages/GrantMilestonesAndUpdates/screens/MilestonesAndUpdates/VerifyMilestoneUpdateDialog.tsx
  components/Pages/GrantMilestonesAndUpdates/screens/NewGrant/index.tsx
  components/Pages/GrantMilestonesAndUpdates/screens/NewMilestone/index.tsx
  components/Pages/ProgramRegistry/AddProgram.tsx
  components/Pages/ProgramRegistry/ProgramDetailsDialog.tsx
  components/Pages/Project/Impact/EndorsementDialog.tsx
  components/Pages/Project/Impact/VerifyImpactDialog.tsx
  utilities/sanitize.ts
Labels: on review

#284 feat: Try static sitemap for projects and grants
  public/sitemap-1.xml
Labels: enhancement

#268 feat: Group by programs on community grants page
  components/CommunityGrants.tsx
  utilities/indexer.ts
  utilities/sdk/communities/getGrants.ts
  utilities/sdk/communities/getPrograms.ts
Labels: bug, enhancement

#287 feat: Milestones report enhancements + stats
  app/[communityId]/admin/milestones-report/loading.tsx
  app/[communityId]/admin/milestones-report/page.tsx
  components/Pages/Admin/ProgramDropdown.tsx
  components/Pages/Admin/ReportMilestonePage.tsx
  utilities/pages.ts
Labels: enhancement

#288 feat: Grant Programs to grants linking, Milestones report enhancement
  app/[communityId]/admin/milestones-report/loading.tsx
  app/[communityId]/admin/milestones-report/page.tsx
  components/CommunityGrants.tsx
  components/Pages/Admin/ProgramDropdown.tsx
  components/Pages/Admin/ReportMilestonePage.tsx
  utilities/indexer.ts
  utilities/pages.ts
  utilities/sdk/communities/getGrants.ts
  utilities/sdk/communities/getPrograms.ts
Labels: enhancement

#294 fix: Update filter by program UI
  components/CommunityGrants.tsx
Labels: enhancement

#298 feat: Disable apply btn if inactive
  components/Pages/ProgramRegistry/ProgramList.tsx
Labels: enhancement

#303 remove: Impact criteria questions
  components/Pages/GrantMilestonesAndUpdates/screens/NewGrant/index.tsx
  components/Pages/Grants/ImpactCriteria/index.tsx
Labels: enhancement

#318 feat: milestone evaluations
  components/Dialogs/ReasonsModal.tsx
  components/Pages/Admin/ReportMilestonePage.tsx
Labels: enhancement

#319 Add milestone evaluation ratings by LLM on the admin reports
  components/Dialogs/ReasonsModal.tsx
  components/Pages/Admin/ReportMilestonePage.tsx
Labels: enhancement

#321 feat: allow multiple models for reasoning
  components/Dialogs/ReasonsModal.tsx
  components/Pages/Admin/ReportMilestonePage.tsx
Labels: enhancement

#322 feat: Handle multiple models
  components/Dialogs/ReasonsModal.tsx
  components/Pages/Admin/ReportMilestonePage.tsx
Labels: enhancement

#331 feat: Partition sitemaps for SEO + disable sentry env
  .env.example
  app/sitemaps/projects/sitemap.ts
  public/sitemap.xml
Labels: enhancement
